// Banco de palavras com níveis de dificuldade para cada idioma
const palavras = {
  pt: [
    { palavra: "sujeito", dicaInicial: "Parte principal da oração.", dicaCompravel: "Quem ou o que realiza a ação do verbo." },
    { palavra: "predicado", dicaInicial: "Complementa o sujeito na oração.", dicaCompravel: "Informa o que o sujeito faz, sofre ou é." },
    { palavra: "substantivo", dicaInicial: "Classe gramatical.", dicaCompravel: "Nomeia seres, objetos, lugares ou sentimentos." },
    { palavra: "adjetivo", dicaInicial: "Caracteriza ou qualifica um substantivo.", dicaCompravel: "Exemplo: bonito, grande, veloz." },
    { palavra: "verbo", dicaInicial: "Indica uma ação, estado ou fenômeno.", dicaCompravel: "Pode ser conjugado em tempos verbais." },
    { palavra: "advérbio", dicaInicial: "Modifica o verbo, adjetivo ou outro advérbio.", dicaCompravel: "Exemplo: rapidamente, muito, ontem." },
    { palavra: "sílaba", dicaInicial: "Unidade fonética de uma palavra.", dicaCompravel: "Pode ser tônica (forte) ou átona (fraca)." },
    { palavra: "parágrafo", dicaInicial: "Unidade de um texto.", dicaCompravel: "Conjunto de frases que desenvolvem uma ideia." },
    { palavra: "metáfora", dicaInicial: "Figura de linguagem.", dicaCompravel: "Comparação implícita entre conceitos." },
    { palavra: "sinônimo", dicaInicial: "Palavra com significado semelhante.", dicaCompravel: "Exemplo: bonito e belo." },
    { palavra: "antônimo", dicaInicial: "Palavra com significado oposto.", dicaCompravel: "Exemplo: bonito e feio." },
    { palavra: "crônica", dicaInicial: "Gênero textual curto.", dicaCompravel: "Retrata situações do cotidiano com linguagem leve." },
    { palavra: "poesia", dicaInicial: "Forma de expressão artística.", dicaCompravel: "Geralmente escrita em versos, com ritmo e rima." },
    { palavra: "prosa", dicaInicial: "Texto com linguagem comum.", dicaCompravel: "Exemplo: romances, contos, crônicas." },
    { palavra: "ortografia", dicaInicial: "Norma de escrita correta.", dicaCompravel: "Regras para grafar palavras corretamente." },
    { palavra: "pontuação", dicaInicial: "Conjunto de sinais gráficos.", dicaCompravel: "Usado para organizar e interpretar o texto." },
    { palavra: "radical", dicaInicial: "Parte invariável de uma palavra.", dicaCompravel: "Base que dá origem às palavras derivadas." },
    { palavra: "paroxítona", dicaInicial: "Classificação de palavras.", dicaCompravel: "A penúltima sílaba é tônica." },
    { palavra: "oxítona", dicaInicial: "Classificação de palavras.", dicaCompravel: "A última sílaba é tônica." },
    { palavra: "paradoxo", dicaInicial: "Figura de linguagem.", dicaCompravel: "Afirmação que contém ideias contraditórias." },
    { palavra: "hipérbole", dicaInicial: "Figura de linguagem.", dicaCompravel: "Usada para exagerar uma ideia ou emoção." },
    { palavra: "personificação", dicaInicial: "Figura de linguagem.", dicaCompravel: "Atribui características humanas a seres inanimados." },
    { palavra: "pleonasmo", dicaInicial: "Recurso de reforço de uma ideia.", dicaCompravel: "Exemplo: subir para cima." },
    { palavra: "onomatopeia", dicaInicial: "Figura de linguagem.", dicaCompravel: "Imita sons através de palavras." },
    { palavra: "eufemismo", dicaInicial: "Suaviza uma expressão forte.", dicaCompravel: "Exemplo: ele partiu (em vez de morreu)." },
    { palavra: "paralelismo", dicaInicial: "Repetição de estrutura sintática.", dicaCompravel: "Compara ou organiza ideias semelhantes." },
    { palavra: "coerência", dicaInicial: "Qualidade de um texto bem estruturado.", dicaCompravel: "Garante sentido lógico ao texto." },
    { palavra: "coesão", dicaInicial: "Conexão entre partes do texto.", dicaCompravel: "Usa pronomes, conjunções e outros recursos." },
    { palavra: "narrador", dicaInicial: "Quem conta a história.", dicaCompravel: "Pode ser em 1ª ou 3ª pessoa." },
    { palavra: "oração", dicaInicial: "Unidade sintática com verbo.", dicaCompravel: "Pode ser principal ou subordinada." },
    { palavra: "adjunto", dicaInicial: "Termo acessório da oração.", dicaCompravel: "Complementa ou explica o núcleo." },
    { palavra: "aposto", dicaInicial: "Explica ou detalha outro termo.", dicaCompravel: "Pode ser usado para definir ou enumerar." },
    { palavra: "sujeito oculto", dicaInicial: "Não está explícito na oração.", dicaCompravel: "Pode ser identificado pelo contexto." },
    { palavra: "predicativo", dicaInicial: "Qualifica o sujeito ou objeto.", dicaCompravel: "Aparece com verbos de ligação." },
    { palavra: "morfologia", dicaInicial: "Estudo das classes gramaticais.", dicaCompravel: "Analisa a estrutura das palavras." },
    { palavra: "sintaxe", dicaInicial: "Estudo das funções dos termos.", dicaCompravel: "Organização e relação entre palavras." },
    { palavra: "fábula", dicaInicial: "Texto com ensinamento moral.", dicaCompravel: "Geralmente protagonizado por animais." },
    { palavra: "aliteração", dicaInicial: "Repetição de sons consonantais.", dicaCompravel: "Exemplo: vozes veladas veludosas." },
    { palavra: "metonímia", dicaInicial: "Substituição de um termo por outro.", dicaCompravel: "Exemplo: ler Machado de Assis (obra pelo autor)." },
    { palavra: "clímax", dicaInicial: "Momento de maior tensão.", dicaCompravel: "Usado em narrativas para intensificar a emoção." },
    { palavra: "denotação", dicaInicial: "Sentido literal da palavra.", dicaCompravel: "Usada de forma objetiva, sem figuras." },
    { palavra: "conotação", dicaInicial: "Sentido figurado da palavra.", dicaCompravel: "Usada para criar significados simbólicos." },
    { palavra: "elipse", dicaInicial: "Omissão de elementos na frase.", dicaCompravel: "Pode ser entendida pelo contexto." },
    { palavra: "prosopopeia", dicaInicial: "Figura de linguagem.", dicaCompravel: "Atribui vida a coisas inanimadas." },
    { palavra: "romantismo", dicaInicial: "Movimento literário.", dicaCompravel: "Valoriza o sentimentalismo e o nacionalismo." },
    { palavra: "realismo", dicaInicial: "Movimento literário.", dicaCompravel: "Critica a sociedade e foca no real." },
    { palavra: "simbolismo", dicaInicial: "Movimento literário.", dicaCompravel: "Foca na subjetividade e nos símbolos." },
    { palavra: "modernismo", dicaInicial: "Movimento literário.", dicaCompravel: "Rompimento com o passado e inovação." },
    { palavra: "barroco", dicaInicial: "Estilo literário e artístico.", dicaCompravel: "Foco no contraste e na dualidade." },
    { palavra: "verossimilhança", dicaInicial: "Aparência de verdade.", dicaCompravel: "Usada para tornar narrativas críveis." },
    { palavra: "hipérbato", dicaInicial: "Inversão da ordem normal das palavras.", dicaCompravel: "Exemplo: das dores do mundo se queixava o poeta." },
    { palavra: "alegoria", dicaInicial: "Figura de linguagem.", dicaCompravel: "Representa algo abstrato com elementos concretos." },
    { palavra: "vocativo", dicaInicial: "Chamamento direto.", dicaCompravel: "Usado para invocar ou dirigir-se a alguém." },
    { palavra: "oração subordinada", dicaInicial: "Depende de outra oração.", dicaCompravel: "Pode ser substantiva, adjetiva ou adverbial." }
  ],
  en: [
    { palavra: "verb to be", dicaInicial: "Verbo referente a ser ou estar.", dicaCompravel: "Base: am, is, are." },
    { palavra: "simple present", dicaInicial: "Usado para ações habituais.", dicaCompravel: "Exemplo: I work every day." },
    { palavra: "simple past", dicaInicial: "Indica ações concluídas no passado.", dicaCompravel: "Exemplo: She went to the park." },
    { palavra: "present continuous", dicaInicial: "Ações em progresso no presente.", dicaCompravel: "Exemplo: They are playing soccer." },
    { palavra: "past continuous", dicaInicial: "Ações em progresso no passado.", dicaCompravel: "Exemplo: I was reading a book." },
    { palavra: "future tense", dicaInicial: "Expressa ações no futuro.", dicaCompravel: "Exemplo: I will travel tomorrow." },
    { palavra: "modal verbs", dicaInicial: "Usados para indicar possibilidade, obrigação, etc.", dicaCompravel: "Exemplos: can, must, should, may." },
    { palavra: "adjective", dicaInicial: "Palavra que descreve substantivos.", dicaCompravel: "Exemplo: big, beautiful, interesting." },
    { palavra: "adverb", dicaInicial: "Palavra que descreve verbos, adjetivos ou outros advérbios.", dicaCompravel: "Exemplo: quickly, very, yesterday." },
    { palavra: "noun", dicaInicial: "Refere-se a pessoas, lugares ou coisas.", dicaCompravel: "Exemplo: table, city, teacher." },
    { palavra: "pronoun", dicaInicial: "Substitui um substantivo.", dicaCompravel: "Exemplo: I, you, he, she, it, we, they." },
    { palavra: "article", dicaInicial: "Palavra usada antes de um substantivo.", dicaCompravel: "Exemplos: a, an, the." },
    { palavra: "conjunction", dicaInicial: "Palavra que conecta ideias ou frases.", dicaCompravel: "Exemplo: and, but, because, although." },
    { palavra: "preposition", dicaInicial: "Indica a relação entre palavras.", dicaCompravel: "Exemplo: in, on, at, under." },
    { palavra: "interjection", dicaInicial: "Expressa emoções ou exclamações.", dicaCompravel: "Exemplo: Wow! Oh! Oops!" },
    { palavra: "present perfect", dicaInicial: "Ações que começaram no passado e continuam.", dicaCompravel: "Exemplo: She has lived here since 2010." },
    { palavra: "past perfect", dicaInicial: "Ações que ocorreram antes de outra ação no passado.", dicaCompravel: "Exemplo: I had finished my work before dinner." },
    { palavra: "future perfect", dicaInicial: "Ações que estarão completas no futuro.", dicaCompravel: "Exemplo: By 2025, I will have graduated." },
    { palavra: "phrasal verbs", dicaInicial: "Verbo + preposição/advérbio.", dicaCompravel: "Exemplo: look up, turn on, give up." },
    { palavra: "imperative", dicaInicial: "Usado para dar ordens ou instruções.", dicaCompravel: "Exemplo: Open the door, please." },
    { palavra: "comparative", dicaInicial: "Forma de comparação entre dois itens.", dicaCompravel: "Exemplo: taller, more beautiful." },
    { palavra: "superlative", dicaInicial: "Indica o grau mais alto de comparação.", dicaCompravel: "Exemplo: tallest, most interesting." },
    { palavra: "synonym", dicaInicial: "Palavras com significados semelhantes.", dicaCompravel: "Exemplo: happy e glad." },
    { palavra: "antonym", dicaInicial: "Palavras com significados opostos.", dicaCompravel: "Exemplo: big e small." },
    { palavra: "conditional sentences", dicaInicial: "Expressa condições e resultados.", dicaCompravel: "Exemplo: If it rains, I will stay home." },
    { palavra: "subject", dicaInicial: "Quem ou o que realiza a ação.", dicaCompravel: "Exemplo: She is reading a book." },
    { palavra: "object", dicaInicial: "Recebe a ação na frase.", dicaCompravel: "Exemplo: He bought a car." },
    { palavra: "active voice", dicaInicial: "O sujeito realiza a ação.", dicaCompravel: "Exemplo: She wrote a letter." },
    { palavra: "passive voice", dicaInicial: "O sujeito sofre a ação.", dicaCompravel: "Exemplo: A letter was written by her." },
    { palavra: "word order", dicaInicial: "Estrutura típica: Sujeito + Verbo + Objeto.", dicaCompravel: "Exemplo: I ate an apple." },
    { palavra: "time expressions", dicaInicial: "Palavras que indicam tempo.", dicaCompravel: "Exemplo: today, tomorrow, last week." },
    { palavra: "idioms", dicaInicial: "Expressões idiomáticas.", dicaCompravel: "Exemplo: It's raining cats and dogs." },
    { palavra: "collocations", dicaInicial: "Palavras frequentemente usadas juntas.", dicaCompravel: "Exemplo: make a decision, do homework." },
    { palavra: "question tags", dicaInicial: "Frases curtas no final de perguntas.", dicaCompravel: "Exemplo: You're coming, aren't you?" },
    { palavra: "quantifiers", dicaInicial: "Indica quantidade.", dicaCompravel: "Exemplo: some, many, few." },
    { palavra: "relative clauses", dicaInicial: "Dá informações adicionais sobre algo.", dicaCompravel: "Exemplo: The man who called is my friend." },
    { palavra: "false cognates", dicaInicial: "Palavras parecidas em português e inglês, mas com significados diferentes.", dicaCompravel: "Exemplo: pretend (fingir)." },
    { palavra: "cognates", dicaInicial: "Palavras parecidas com os mesmos significados.", dicaCompravel: "Exemplo: important e importante." },
    { palavra: "countable nouns", dicaInicial: "Substantivos que podem ser contados.", dicaCompravel: "Exemplo: apple, book." },
    { palavra: "uncountable nouns", dicaInicial: "Substantivos que não podem ser contados.", dicaCompravel: "Exemplo: water, information." },
    { palavra: "infinitive", dicaInicial: "Forma básica de um verbo.", dicaCompravel: "Exemplo: to eat, to go." },
    { palavra: "gerund", dicaInicial: "Verbo usado como substantivo.", dicaCompravel: "Exemplo: Swimming is fun." },
    { palavra: "collocation", dicaInicial: "Combinações naturais de palavras.", dicaCompravel: "Exemplo: heavy rain, fast food." },
    { palavra: "interrogative", dicaInicial: "Palavras usadas para fazer perguntas.", dicaCompravel: "Exemplo: Who, what, when, where, why." },
    { palavra: "polite expressions", dicaInicial: "Usadas para ser educado.", dicaCompravel: "Exemplo: Could you please help me?" },
    { palavra: "abbreviations", dicaInicial: "Formas curtas de palavras ou frases.", dicaCompravel: "Exemplo: ASAP (as soon as possible)." },
    { palavra: "homophones", dicaInicial: "Palavras que têm o mesmo som, mas significados diferentes.", dicaCompravel: "Exemplo: here e hear." },
    { palavra: "contractions", dicaInicial: "Forma encurtada de duas palavras.", dicaCompravel: "Exemplo: don't (do not), it's (it is)." },
    { palavra: "greetings", dicaInicial: "Formas de cumprimentar.", dicaCompravel: "Exemplo: Hello, how are you?" }
  ],
};

